name: Compile

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: python build.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4.4.0
      with:
        name: flip_fluids_addon.zip
        path: D:\a\Blender-FLIP-Fluids\Blender-FLIP-Fluids\build\bl_flip_fluids\flip_fluids_addon
